name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose -- --color=always
    - name: Run tests
      run: cargo test --verbose -- --color=always
